# Generated by Django 4.0.1 on 2022-01-31 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_category_lesson_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='home_work',
            field=models.CharField(default=1, max_length=150, verbose_name='Домашнее задание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lessons.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
