# Generated by Django 4.0.1 on 2022-01-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lesson_home_work_alter_lesson_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='home_work',
            field=models.URLField(max_length=150, verbose_name='Домашнее задание'),
        ),
    ]
